font_family CaskaydiaCove NF
font_size 15.5
#cursor_trail 100
hide_window_decorations yes
tab_bar_style powerline
tab_bar_min_tabs 1
tab_powerline_style round
shell /usr/bin/bash
background_opacity 0.755
dynamic_background_opacity yes
background_blur 1
window_padding_width 8


# BEGIN_KITTY_THEME
# Gruvbox Dark Soft
include current-theme.conf
# END_KITTY_THEME
